# Generated by Django 5.2.5 on 2025-09-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
