# Generated by Django 5.2.5 on 2025-09-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_car_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
