# Generated by Django 5.2.5 on 2025-09-22 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_driver_rating_alter_car_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uid', models.BigIntegerField(db_index=True)),
                ('category', models.CharField(default='F1', max_length=8)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.car')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.driver')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.track')),
            ],
        ),
        migrations.CreateModel(
            name='LiveLap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField()),
                ('lap_time_ms', models.IntegerField(blank=True, null=True)),
                ('sector1_ms', models.IntegerField(blank=True, null=True)),
                ('sector2_ms', models.IntegerField(blank=True, null=True)),
                ('sector3_ms', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='core.livesession')),
            ],
        ),
        migrations.CreateModel(
            name='LiveTelemetryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_ms', models.IntegerField()),
                ('speed_kmh', models.FloatField()),
                ('rpm', models.IntegerField(blank=True, null=True)),
                ('throttle', models.FloatField(blank=True, null=True)),
                ('brake', models.FloatField(blank=True, null=True)),
                ('gear', models.IntegerField(blank=True, null=True)),
                ('lap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.livelap')),
            ],
        ),
    ]
