# Generated by Django 5.2.5 on 2025-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_livesession_livelap_livetelemetrypoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='car',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='category',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='track',
        ),
        migrations.AddField(
            model_name='livesession',
            name='car_label',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='driver_label',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='track_label',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='session_uid',
            field=models.BigIntegerField(unique=True),
        ),
    ]
