# Generated by Django 5.2.5 on 2025-09-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_livesession_car_remove_livesession_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='car_label',
            field=models.CharField(blank=True, default='—', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='driver_label',
            field=models.CharField(blank=True, default='—', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='session_uid',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='track_label',
            field=models.CharField(blank=True, default='—', max_length=120, null=True),
        ),
    ]
